language: android
cache: false

sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
    - android-25
    - sys-img-armeabi-v7a-android-25
    
jdk: oraclejdk8
os:
  - linux

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

branches:
  only:
  - master
  - develop
  - feature/configure_travis

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew;
  
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew build connectedCheck